set dotenv-load

# Build firmware
build: _sdkconfig-local
    (. ~/esp/esp-idf/export.sh && cd ./firmware && idf.py build)

# Clean artifacts and build firmware
build--clean: _sdkconfig-local
    (. ~/esp/esp-idf/export.sh && cd ./firmware && idf.py clean build)

# Build and flash the firmware to StackChan
flash: _sdkconfig-local
    (. ~/esp/esp-idf/export.sh && cd ./firmware && idf.py build flash)

# Clean firmware build artifacts, build it and flash it to StackChan
flash--clean: _sdkconfig-local
    (. ~/esp/esp-idf/export.sh && cd ./firmware && idf.py clean build flash)

# Regenerate the git-ignored sdkconfig overlay from .env so the private-server
# URL is baked into the firmware at build time without ever being committed.
_sdkconfig-local:
    #!/usr/bin/env bash
    set -euo pipefail
    : "${PRIVATE_SERVER_URL:?PRIVATE_SERVER_URL is not set — copy .env.example to .env and set it}"
    base="${PRIVATE_SERVER_URL%/}"
    overlay=firmware/sdkconfig.defaults.local
    tmp="$(mktemp)"
    {
        echo '# GENERATED by `just` from the repo-root .env — do not edit, do not commit.'
        echo '# Auto-applied as an sdkconfig overlay by firmware/CMakeLists.txt.'
        printf 'CONFIG_STACKCHAN_SERVER_URL="%s"\n' "$base"
        printf 'CONFIG_OTA_URL="%s/xiaozhi/ota/"\n' "$base"
    } > "$tmp"
    if ! cmp -s "$tmp" "$overlay" 2>/dev/null; then mv "$tmp" "$overlay"; else rm "$tmp"; fi
    # sdkconfig defaults only apply when sdkconfig is (re)generated — patch an
    # existing sdkconfig so .env changes take effect on the next build.
    if [ -f firmware/sdkconfig ] && { ! grep -qxF "CONFIG_STACKCHAN_SERVER_URL=\"$base\"" firmware/sdkconfig || ! grep -qxF "CONFIG_OTA_URL=\"$base/xiaozhi/ota/\"" firmware/sdkconfig; }; then
        sed -i '' -e "s|^CONFIG_STACKCHAN_SERVER_URL=.*|CONFIG_STACKCHAN_SERVER_URL=\"$base\"|" -e "s|^CONFIG_OTA_URL=.*|CONFIG_OTA_URL=\"$base/xiaozhi/ota/\"|" firmware/sdkconfig
        echo "firmware/sdkconfig: updated server URLs from .env"
    fi
